version: '3.8'
services:
  langflow:
    build: .
    ports:
      - "7860:7860"
    volumes:
      - langflow_data:/data
      - langflow_config:/config
    environment:
      - LANGFLOW_CONFIG=/config/langflow.conf

volumes:
  langflow_data:
  langflow_config: